name: Deploy on Commit

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1  # Use v1 instead of v2

      - name: Set up Git
        run: |
          git config --global user.email "kushilkumar000@gmail.com"
          git config --global user.name "kushilkumar"

      - name: Check Commit Message
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          if [[ $MESSAGE == *"YES"* ]]; then
            DEPLOY_BRANCH="FE"
          else
            DEPLOY_BRANCH="QA"
          fi

      - name: Deploy to Branch
        run: |
          git checkout $DEPLOY_BRANCH
          git merge dev
          git push "https://kushilkumar:${{ secrets.GITHUB_TOKEN }}@github.com/kushilkumar/githubrepo.git" $DEPLOY_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
