name: Deploy on Dev Commit

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git user email and name
        run: |
          git config --global user.email "kushilkumar000@gmail.com"
          git config --global user.name "kushilkumar"

      - name: Determine deploy branch
        id: determine_branch
        run: echo "::set-output name=branch::$(if [[ $(git log -1 --pretty=%B) == *'[deploy-yes]'* ]]; then echo 'FE'; else echo 'QA'; fi)"

      - name: Deploy
        run: |
          if [ "${{ steps.determine_branch.outputs.branch }}" == "FE" ]; then
            git push origin HEAD:FE
          elif [ "${{ steps.determine_branch.outputs.branch }}" == "QA" ]; then
            git push origin HEAD:QA
          else
            echo "No deploy action specified."
          fi
