name: File Deployment Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Determine deployment branch
      run: |
        commit_message=$(git log -1 --pretty=format:"%s")
        echo "::set-output name=deploy_branch::$commit_message"

    - name: Deploy to FE or QA
      run: |
        commit_message="${{ steps.deploy.outputs.deploy_branch }}"
        if [[ $commit_message == *"YES"* ]]; then
          git checkout -b FE
          git push origin HEAD:FE
        elif [[ $commit_message == *"NO"* ]]; then
          git checkout -b QA
          git push origin HEAD:QA
        else
          echo "Invalid commit message. Please include 'YES' or 'NO' in the commit message."
          exit 1
        fi

    - name: Cleanup
      run: git checkout dev
