name: Print GitHub Environment

on:
  push:
    branches:
      - dev

jobs:
  print_environment:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: git config --global user.email "kushilkumar000@gmail.com" && git config --global user.name "kushilkumar"

    - name: Print Environment Variables
      run: |
        echo "GitHub Environment Variables:"
        env | grep GITHUB

    - name: Print System Information
      run: |
        echo "System Information:"
        uname -a
