name: Deployment Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Determine Deployment Branch
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == *yes* ]]; then
            DEPLOY_BRANCH="FE"
          else
            DEPLOY_BRANCH="QA"
          fi
          echo "Deploying to $DEPLOY_BRANCH branch"

      - name: Deploy
        run: |
          git push origin HEAD:$DEPLOY_BRANCH
