name: File Deployment Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Determine deployment branch
      run: |
        commit_message=$(git log -1 --pretty=format:"%s")

        # Set a default commit message if empty
        commit_message="${commit_message:-DEFAULT}"

        echo "::set-output name=deploy_branch::$commit_message"

    - name: Deploy to FE or QA
      run: |
        commit_message="${{ steps.deploy.outputs.deploy_branch }}"
        if [[ $commit_message == *"YES"* ]]; then
          git checkout -b FE
          git push origin HEAD:FE
        else
          # If commit message is empty or doesn't contain "YES", deploy to QA
          git checkout -b QA
          git push origin HEAD:QA
        fi
