name: File Deployment Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "kushilkumar000@gmail.com"
        git config --global user.name "kushilkumar"

    - name: Determine deployment branch
      id: check_commit_message
      run: echo "::set-output name=deploy_branch::$(echo ${{ github.event.head_commit.message }} | tr '[:upper:]' '[:lower:]')"

    - name: Deploy to FE or QA
      run: |
        if [[ "${{ steps.check_commit_message.outputs.deploy_branch }}" == "yes" ]]; then
          git checkout -b FE
        elif [[ "${{ steps.check_commit_message.outputs.deploy_branch }}" == "no" ]]; then
          git checkout -b QA
        else
          echo "Invalid commit message. Please use 'YES' or 'NO'."
          exit 1
        fi
        git push origin HEAD

    - name: Cleanup
      run: git checkout dev
