name: File Deployment Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "kushilkumar000@gmail.com"
        git config --global user.name "kushilkumar"

    - name: Determine deployment branch
      id: check_commit_message
      run: |
        commit_message=$(git log -1 --pretty=format:"%s")
        echo "::set-output name=deploy_branch::$commit_message"

    - name: Deploy to FE or QA
      run: |
        commit_message="${{ steps.check_commit_message.outputs.deploy_branch }}"
        if [[ $commit_message == *"YES"* ]]; then
          git checkout -b FE
        elif [[ $commit_message == *"NO"* ]]; then
          git checkout -b QA
        else
          echo "Invalid commit message. Please include 'YES' or 'NO' in the commit message."
          exit 1
        fi
        git push origin HEAD

    - name: Cleanup
      run: git checkout dev
